version: "3.5"

services:
  scrapy:
    container_name: scrapy
    build:
      context: ./app
    environment:
      MYSQL_USER: secret
      MYSQL_PASSWORD: secret
      MYSQL_HOST: 255.255.255.255
      MYSQL_DB: secret
    command: python ./runspiders.py